### ISSUE TITLE
error  when running `example/nx_app.py` when only grapheditor is installed

### ISSUE THREAD

**Issue by baugetfa** [openalea/grapheditor#10]
After creating an environment as follow:
```
conda create -n grapheditor python=3.9 openalea.grapheditor networkx -c openalea3 -c conda-forge
```

Then running `python nx_app.py` leads to the following error:
```
Traceback (most recent call last):
  File "/home/fabrice/miniconda3/envs/grapheditor/lib/python3.9/site-packages/qtpy/__init__.py", line 252, in <module>
    from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fabrice/Documents/Openalea_Dev/grapheditor/examples/networkx/nx_app.py", line 15, in <module>
    from openalea.grapheditor.all import  Observed, GraphAdapterBase
  File "/home/fabrice/miniconda3/envs/grapheditor/lib/python3.9/site-packages/OpenAlea.GraphEditor-2.2.0-py3.9.egg/openalea/grapheditor/all.py", line 21, in <module>
    from openalea.grapheditor.edgefactory import LinearEdgePath, SplineEdgePath
  File "/home/fabrice/miniconda3/envs/grapheditor/lib/python3.9/site-packages/OpenAlea.GraphEditor-2.2.0-py3.9.egg/openalea/grapheditor/edgefactory.py", line 22, in <module>
    from qtpy import QtCore, QtGui
  File "/home/fabrice/miniconda3/envs/grapheditor/lib/python3.9/site-packages/qtpy/__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError()
qtpy.QtBindingsNotFoundError: No Qt bindings could be found
```

Note that this error does not happen when we create a full visualea environment:
```
conda create -n visualea2 openalea.visualea openalea.plantgl networkx -c openalea3 -c conda-forge
```

That probably come from the vpltk removing.

**Comment by pradal** [comment]
It misses pyqt that may be installed by qtconsole

**Comment by baugetfa** [comment]
Ok. This is it, but would have expect qtconsole in the dependencies. Well I will update the readme and add qtconsole to the installation lines.

**Comment by baugetfa** [comment]
Readme updated with qtconsole to be installed
